
# <http://elasticsearch.org/guide/en/elasticsearch/reference/current/setup-configuration.html>

cluster.name: cluster

#node.name: "node1"

node.master: true
node.data: true

#node.rack: rack314
#node.max_local_storage_nodes: 1

# Set the number of shards (splits) of an index (5 by default):
index.number_of_shards: 1

# Set the number of replicas (additional copies) of an index (1 by default):
index.number_of_replicas: 1

# Path to directory containing configuration (this file and logging.yml):
path.conf: ./config

# Path to directory where to store index data allocated for this node.
path.data: ./var/data

# Can optionally include more than one location, causing data to be striped across
# the locations (a la RAID 0) on a file level, favouring locations with most free
# space on creation. For example:
#
#path.data: /path/to/data1,/path/to/data2

# Path to temporary files:
path.work: ./var/tmp

# Path to log files:
path.logs: ./var/logs

# Path to where plugins are installed:
path.plugins: ./plugins

# If a plugin listed here is not installed for current node, the node will not start.
#plugin.mandatory: mapper-attachments,lang-groovy

# Set this property to true to lock the memory:
#bootstrap.mlockall: true

# Set both 'bind_host' and 'publish_host':
network.host: _local_

# Set a custom port for the node to node communication (9300 by default):
transport.tcp.port: 9300

# Enable compression for all communication between nodes (disabled by default):
#transport.tcp.compress: true

# Set a custom port to listen for HTTP traffic:
http.port: 9200

# Set a custom allowed content length:
#http.max_content_length: 100mb

# Disable HTTP completely:
#http.enabled: false

http.compression: true

# Enable or disable cross-origin resource sharing
http.cors.enabled: false
#http.cors.allow-origin: *


# There are several types of gateway implementations. For more information, see
# <http://elasticsearch.org/guide/en/elasticsearch/reference/current/modules-gateway.html>.

#gateway.type: local
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 1


#cluster.routing.allocation.node_concurrent_recoveries: 2

# Set to throttle throughput when recovering (eg. 100mb, by default 20mb):
#indices.recovery.max_bytes_per_sec: 20mb

# Set to limit the number of open concurrent streams when
# recovering a shard from a peer:
#indices.recovery.concurrent_streams: 5


# For more information, see
# <http://elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html>

#discovery.zen.minimum_master_nodes: 1
#discovery.zen.ping.timeout: 3s

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["localhost"]


# Shard level query and fetch threshold logging.

#index.search.slowlog.threshold.query.warn: 10s
#index.search.slowlog.threshold.query.info: 5s
#index.search.slowlog.threshold.query.debug: 2s
#index.search.slowlog.threshold.query.trace: 500ms

#index.search.slowlog.threshold.fetch.warn: 1s
#index.search.slowlog.threshold.fetch.info: 800ms
#index.search.slowlog.threshold.fetch.debug: 500ms
#index.search.slowlog.threshold.fetch.trace: 200ms

#index.indexing.slowlog.threshold.index.warn: 10s
#index.indexing.slowlog.threshold.index.info: 5s
#index.indexing.slowlog.threshold.index.debug: 2s
#index.indexing.slowlog.threshold.index.trace: 500ms

#monitor.jvm.gc.young.warn: 1000ms
#monitor.jvm.gc.young.info: 700ms
#monitor.jvm.gc.young.debug: 400ms

monitor.jvm.gc.old.warn: 10s
#monitor.jvm.gc.old.info: 5s
#monitor.jvm.gc.old.debug: 2s

#http.jsonp.enable: true

##

action.auto_create_index: false
index.mapper.dynamic: false

index.refresh_interval: 30
